In [170]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math


In [171]:
df=pd.read_csv("iris_dataset.csv")
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [172]:
# df1=df[['sepal length (cm)','sepal width (cm)','target','petal length (cm)','petal width (cm)']]
# df1

In [173]:
df1=df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
df1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [174]:
P_test=df.iloc[149]
P_test

sepal length (cm)    5.9
sepal width (cm)     3.0
petal length (cm)    5.1
petal width (cm)     1.8
target               2.0
Name: 149, dtype: float64

In [175]:
df2=df1.drop(df1.index[149])
df2

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3

[149 rows x 4 columns]

In [176]:
X=P_test.iloc[0]
Y=P_test.iloc[1]
Z=P_test.iloc[2]
T=P_test.iloc[3]
(X,Y,Z,T)

(np.float64(5.9), np.float64(3.0), np.float64(5.1), np.float64(1.8))

In [177]:
list_Euclidean_Distance=[]
for col in range(len(df2)):
   list_Euclidean_Distance.append(math.sqrt( ((X-df2.iloc[col,0])**2)+((Y-df2.iloc[col,1])**2)+((Z-df2.iloc[col,2])**2)+((T-df2.iloc[col,3])**2)))
list_Euclidean_Distance

[4.1400483088968905,
 4.153311931459037,
 4.298837052040936,
 4.149698784249286,
 4.173727350941841,
 3.818376618407356,
 4.217819341792628,
 4.060788100849391,
 4.302324952859791,
 4.106093033529562,
 4.03236903073119,
 4.022437072223753,
 4.217819341792628,
 4.631414470763764,
 4.33358973600409,
 4.113392760240626,
 4.178516483155236,
 4.102438299353203,
 3.806573262134856,
 4.060788100849391,
 3.8118237105091834,
 4.006245124802025,
 4.628174586162454,
 3.738983819167983,
 3.7643060449437424,
 3.9522145690739006,
 3.896151947755631,
 4.03236903073119,
 4.110960958218893,
 4.036087214122113,
 4.00374824383352,
 3.915354390090378,
 4.189272013130682,
 4.224926034855522,
 4.065710270051224,
 4.315089802078283,
 4.172529209005013,
 4.235563716909474,
 4.387482193696061,
 4.039801975344831,
 4.2130748865881795,
 4.374928570845472,
 4.3920382511995495,
 3.8405728739343035,
 3.671511950137164,
 4.141255848169731,
 4.011234224026316,
 4.240283009422838,
 4.045985664828781,
 4.14125584816973

In [178]:
df3=pd.DataFrame(list_Euclidean_Distance)
df3.columns=['Euclidean Distance']
df3

Euclidean Distance
0              4.140048
1              4.153312
2              4.298837
3              4.149699
4              4.173727
..                  ...
144            1.256981
145            0.948683
146            0.655744
147            0.640312
148            0.768115

[149 rows x 1 columns]

In [179]:
idx = np.argsort(list_Euclidean_Distance)[:3]
idx

array([127, 138, 142])

In [180]:
np.array(list_Euclidean_Distance)[idx]

array([0.28284271, 0.31622777, 0.33166248])

In [181]:
list_target=[]
list_target=df["target"][idx]
list_target

127    2
138    2
142    2
Name: target, dtype: int64

قسمت 2

In [182]:
# list_mean=[]
# list_std=[]
# for col in df2.columns:
#     list_mean.append(df2[col].mean())
#     list_std.append(df2[col].std())
    
means=df1.mean()
standard_dv=df1.std()
means

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [ ]:
z_score=(df1-means)/standard_dv
z_score

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.897674          1.015602          -1.335752         -1.311052
1            -1.139200         -0.131539          -1.335752         -1.311052
2            -1.380727          0.327318          -1.392399         -1.311052
3            -1.501490          0.097889          -1.279104         -1.311052
4            -1.018437          1.245030          -1.335752         -1.311052
..                 ...               ...                ...               ...
145           1.034539         -0.131539           0.816859          1.443994
146           0.551486         -1.278680           0.703564          0.919223
147           0.793012         -0.131539           0.816859          1.050416
148           0.430722          0.786174           0.930154          1.443994
149           0.068433         -0.131539           0.760211          0.788031

[150 rows x 4 columns]

In [191]:
list_Euclidean_Distance_normal=[]
for col in range(len(z_score)):
   list_Euclidean_Distance_normal.append(math.sqrt( ((X-z_score.iloc[col,0])**2)+((Y-z_score.iloc[col,1])**2)+((Z-z_score.iloc[col,2])**2)+((T-z_score.iloc[col,3])**2)))
list_Euclidean_Distance_normal

[10.061995338583092,
 10.509729936791171,
 10.582160109558895,
 10.657200350462098,
 10.101595753566832,
 9.482997703824363,
 10.487208774010824,
 10.155659133081576,
 10.991330780668257,
 10.448813750860019,
 9.701188453212056,
 10.286797715418045,
 10.630271273307983,
 11.14585897738755,
 9.41806256218551,
 9.25725740927054,
 9.634216914237278,
 10.022208698450736,
 9.31140712666087,
 9.872224193721769,
 9.759825666917074,
 9.866281859718272,
 10.57957602094965,
 9.94097006670935,
 10.183230038166394,
 10.359701148197948,
 10.042616984577196,
 9.944374459884761,
 10.028943400520824,
 10.478755562567,
 10.456549486384137,
 9.753105316394317,
 9.80590180062134,
 9.545426444685953,
 10.408852134842038,
 10.371917180427957,
 9.779681162209595,
 10.225522637891286,
 10.956830657854765,
 10.07377831616499,
 10.14068140973775,
 11.404356988163695,
 10.834612795616247,
 9.922948867908598,
 9.687961796649038,
 10.553202277536185,
 9.876253336209526,
 10.63121988556316,
 9.781715474188985,
 10

In [194]:
df_3=pd.DataFrame(list_Euclidean_Distance_normal)
df_3.columns=['Euclidean Distance']
df_3

Euclidean Distance
0             10.061995
1             10.509730
2             10.582160
3             10.657200
4             10.101596
..                  ...
145            7.207724
146            8.186460
147            7.402367
148            7.233835
149            7.979446

[150 rows x 1 columns]

In [195]:
idx = np.argsort(list_Euclidean_Distance_normal)[:3]
idx

array([131, 117, 109])

In [196]:
np.array(list_Euclidean_Distance_normal)[idx]

array([5.18624818, 5.20436291, 5.95719577])

In [197]:
list_target1=[]
list_target1=df["target"][idx]
list_target1

131    2
117    2
109    2
Name: target, dtype: int64

در هر دو حالت پیش بینی درست و از کلاس virginica است